# apfs
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/apfs.util.8
complete -c apfs -s p -d 'Probe the device to determine whether it contains an apfs volume'
complete -c apfs -s k -d 'Return the UUID of the apfs volume on device'
complete -c apfs -s s -d 'Set UUIDs for the container and the volume(s) on the device to new random val…'
complete -c apfs -s B -d 'Bootstrap root container by creating and mounting VM volume and mount preboot…'

