# atos
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/atos.1
complete -c atos -s o -d 'The path to a binary image file in which to look up symbols'
complete -c atos -s p -d 'The process ID or the partial name of a currently executing process in which …'
complete -c atos -o arch -d 'The particular architecure of a binary image file in which to look up symbols'
complete -c atos -s l -d 'The load address of the binary image'
complete -c atos -s s -d 'The slide value of the binary image -- this is the difference between the loa…'
complete -c atos -o printHeader -d 'If a process was specified, the first line of atos output should be a header …'
complete -c atos -o fullPath -d 'Print the full path of the source files'

