# chgrp
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/chgrp.1
complete -c chgrp -s f -d 'The force option ignores errors, except for usage errors and doesn\'t query ab…'
complete -c chgrp -s H -d 'If the R option is specified, symbolic links on the command line are followed'
complete -c chgrp -s h -d 'If the file is a symbolic link, the group ID of the link itself is changed ra…'
complete -c chgrp -s L -d 'If the R option is specified, all symbolic links are followed'
complete -c chgrp -s P -d 'If the R option is specified, no symbolic links are followed'
complete -c chgrp -s R -d 'Change the group ID for the file hierarchies rooted in the files instead of j…'
complete -c chgrp -s n -d 'Interpret the group ID as numeric, avoiding the name lookup'
complete -c chgrp -s v -d 'Cause chgrp chgrp to be verbose, showing files as the group is modified'

