# comm
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/comm.1
complete -c comm -s 1 -d 'Suppress printing of column 1'
complete -c comm -s 2 -d 'Suppress printing of column 2'
complete -c comm -s 3 -d 'Suppress printing of column 3'
complete -c comm -s i -d 'Case insensitive comparison of lines'

