# csdiagnose
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/csdiagnose.1
complete -c csdiagnose -s h -d 'Show this help information'
complete -c csdiagnose -s f -d 'Specify an output path which will hold the file generated by this script'
complete -c csdiagnose -s v -d 'Verbose mode, which prints every command it invokes'

