# date
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/date.1
complete -c date -s d -d 'Set the kernel\'s value for daylight saving time'
complete -c date -s f -d 'Use input_fmt as the format string to parse the new_date provided rather than…'
complete -c date -s j -d 'Do not try to set the date'
complete -c date -s n -d 'By default, if the timed 8 daemon is running, date sets the time on all of th…'
complete -c date -s R -d 'Use RFC 2822 date and time output format'
complete -c date -s r -d 'Print the date and time represented by seconds, where seconds is the number o…'
complete -c date -s t -d 'Set the system\'s value for minutes west of GMT'
complete -c date -s u -d 'Display or set the date in UTC (Coordinated Universal) time'
complete -c date -s v -d 'Adjust (i. e'

