# du
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/du.1
complete -c du -s a -d 'Display an entry for each file in a file hierarchy'
complete -c du -s c -d 'Display a grand total'
complete -c du -s d -d 'Display an entry for all files and directories depth directories deep'
complete -c du -s H -d 'Symbolic links on the command line are followed, symbolic links in file hiera…'
complete -c du -s h -d '"Human-readable" output'
complete -c du -s I -d 'Ignore files and directories matching the specified mask'
complete -c du -s g -d 'Display block counts in 1073741824-byte (1-Gbyte) blocks'
complete -c du -s k -d 'Display block counts in 1024-byte (1-Kbyte) blocks'
complete -c du -s L -d 'Symbolic links on the command line and in file hierarchies are followed'
complete -c du -s m -d 'Display block counts in 1048576-byte (1-Mbyte) blocks'
complete -c du -s P -d 'No symbolic links are followed.  This is the default'
complete -c du -s r -d 'Generate messages about directories that cannot be read, files that cannot be…'
complete -c du -s s -d 'Display an entry for each specified file.  (Equivalent to d Li 0 )'
complete -c du -s x -d 'File system mount points are not traversed'

