# duti
# Autogenerated from man page /usr/local/share/man/man1/duti.1
complete -c duti -s d -d 'display the default handler for  uti and exit'
complete -c duti -s h -d 'print usage and exit'
complete -c duti -s l -d 'display all handlers for  uti and exit'
complete -c duti -s s -d 'set the handler from data provided on the command line'
complete -c duti -s V -d 'print version number and exit'
complete -c duti -s v -d 'verbose output'
complete -c duti -s x -d 'retrieves and prints out information describing the default application for f…'

