# emlog
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/emlog.pl.8
complete -c emlog -s p -d 'Tells emlog to listen on the given local port number, processing the UDP pack…'
complete -c emlog -s l -d 'Tells emlog to process a single line of text then quit'

