# gbase32
# Autogenerated from man page /usr/local/share/man/man1/gbase32.1
complete -c gbase32 -s d -l decode -d 'decode data'
complete -c gbase32 -s i -l ignore-garbage -d 'when decoding, ignore non-alphabet characters'
complete -c gbase32 -s w -l wrap -d 'wrap encoded lines after COLS character (default 76)'
complete -c gbase32 -l help -d 'display this help and exit'
complete -c gbase32 -l version -d 'output version information and exit'

