# gbasename
# Autogenerated from man page /usr/local/share/man/man1/gbasename.1
complete -c gbasename -s a -l multiple -d 'support multiple arguments and treat each as a NAME'
complete -c gbasename -s s -l suffix -d 'remove a trailing SUFFIX; implies -a'
complete -c gbasename -s z -l zero -d 'end each output line with NUL, not newline'
complete -c gbasename -l help -d 'display this help and exit'
complete -c gbasename -l version -d 'output version information and exit EXAMPLES'
complete -c gbasename -s '>'

