# gbasenc
# Autogenerated from man page /usr/local/share/man/man1/gbasenc.1
complete -c gbasenc -l base64 -d 'same as \'base64\' program (RFC4648 section 4)'
complete -c gbasenc -l base64url -d 'file- and url-safe base64 (RFC4648 section 5)'
complete -c gbasenc -l base32 -d 'same as \'base32\' program (RFC4648 section 6)'
complete -c gbasenc -l base32hex -d 'extended hex alphabet base32 (RFC4648 section 7)'
complete -c gbasenc -l base16 -d 'hex encoding (RFC4648 section 8)'
complete -c gbasenc -l base2msbf -d 'bit string with most significant bit (msb) first'
complete -c gbasenc -l base2lsbf -d 'bit string with least significant bit (lsb) first'
complete -c gbasenc -s d -l decode -d 'decode data'
complete -c gbasenc -s i -l ignore-garbage -d 'when decoding, ignore non-alphabet characters'
complete -c gbasenc -s w -l wrap -d 'wrap encoded lines after COLS character (default 76)'
complete -c gbasenc -l z85 -d 'ascii85-like encoding (ZeroMQ spec:32/Z85); when encoding, input length must …'
complete -c gbasenc -l help -d 'display this help and exit'
complete -c gbasenc -l version -d 'output version information and exit'

