# gcat
# Autogenerated from man page /usr/local/share/man/man1/gcat.1
complete -c gcat -s A -l show-all -d 'equivalent to -vET'
complete -c gcat -s b -l number-nonblank -d 'number nonempty output lines, overrides -n'
complete -c gcat -s e -d 'equivalent to -vE'
complete -c gcat -s E -l show-ends -d 'display $ at end of each line'
complete -c gcat -s n -l number -d 'number all output lines'
complete -c gcat -s s -l squeeze-blank -d 'suppress repeated empty output lines'
complete -c gcat -s t -d 'equivalent to -vT'
complete -c gcat -s T -l show-tabs -d 'display TAB characters as ^I'
complete -c gcat -s u -d '(ignored)'
complete -c gcat -s v -l show-nonprinting -d 'use ^ and M- notation, except for LFD and TAB'
complete -c gcat -l help -d 'display this help and exit'
complete -c gcat -l version -d 'output version information and exit EXAMPLES'

