# gchcon
# Autogenerated from man page /usr/local/share/man/man1/gchcon.1
complete -c gchcon -l dereference -d 'affect the referent of each symbolic link (this is the default), rather than …'
complete -c gchcon -s h -l no-dereference -d 'affect symbolic links instead of any referenced file'
complete -c gchcon -s u -l user -d 'set user USER in the target security context'
complete -c gchcon -s r -l role -d 'set role ROLE in the target security context'
complete -c gchcon -s t -l type -d 'set type TYPE in the target security context'
complete -c gchcon -s l -l range -d 'set range RANGE in the target security context'
complete -c gchcon -l no-preserve-root -d 'do not treat \'/\' specially (the default)'
complete -c gchcon -l preserve-root -d 'fail to operate recursively on \'/\''
complete -c gchcon -l reference -d 'use RFILE\'s security context rather than specifying a CONTEXT value'
complete -c gchcon -s R -l recursive -d 'operate on files and directories recursively'
complete -c gchcon -s v -l verbose -d 'output a diagnostic for every file processed '
complete -c gchcon -s H -d 'if a command line argument is a symbolic link to a directory, traverse it'
complete -c gchcon -s L -d 'traverse every symbolic link to a directory encountered'
complete -c gchcon -s P -d 'do not traverse any symbolic links (default)'
complete -c gchcon -l help -d 'display this help and exit'
complete -c gchcon -l version -d 'output version information and exit AUTHOR Written by Russell Coker and Jim M…'

