# gchgrp
# Autogenerated from man page /usr/local/share/man/man1/gchgrp.1
complete -c gchgrp -s c -l changes -d 'like verbose but report only when a change is made'
complete -c gchgrp -s f -l silent -l quiet -d 'suppress most error messages'
complete -c gchgrp -s v -l verbose -d 'output a diagnostic for every file processed'
complete -c gchgrp -l dereference -d 'affect the referent of each symbolic link (this is the default), rather than …'
complete -c gchgrp -s h -l no-dereference -d 'affect symbolic links instead of any referenced file (useful only on systems …'
complete -c gchgrp -l no-preserve-root -d 'do not treat \'/\' specially (the default)'
complete -c gchgrp -l preserve-root -d 'fail to operate recursively on \'/\''
complete -c gchgrp -l reference -d 'use RFILE\'s group rather than specifying a GROUP value'
complete -c gchgrp -s R -l recursive -d 'operate on files and directories recursively '
complete -c gchgrp -s H -d 'if a command line argument is a symbolic link to a directory, traverse it'
complete -c gchgrp -s L -d 'traverse every symbolic link to a directory encountered'
complete -c gchgrp -s P -d 'do not traverse any symbolic links (default)'
complete -c gchgrp -l help -d 'display this help and exit'
complete -c gchgrp -l version -d 'output version information and exit EXAMPLES'

