# gchmod
# Autogenerated from man page /usr/local/share/man/man1/gchmod.1
complete -c gchmod -s c -l changes -d 'like verbose but report only when a change is made'
complete -c gchmod -s f -l silent -l quiet -d 'suppress most error messages'
complete -c gchmod -s v -l verbose -d 'output a diagnostic for every file processed'
complete -c gchmod -l no-preserve-root -d 'do not treat \'/\' specially (the default)'
complete -c gchmod -l preserve-root -d 'fail to operate recursively on \'/\''
complete -c gchmod -l reference -d 'use RFILE\'s mode instead of MODE values'
complete -c gchmod -s R -l recursive -d 'change files and directories recursively'
complete -c gchmod -l help -d 'display this help and exit'
complete -c gchmod -l version -d 'output version information and exit'

