# gchown
# Autogenerated from man page /usr/local/share/man/man1/gchown.1
complete -c gchown -s c -l changes -d 'like verbose but report only when a change is made'
complete -c gchown -s f -l silent -l quiet -d 'suppress most error messages'
complete -c gchown -s v -l verbose -d 'output a diagnostic for every file processed'
complete -c gchown -l dereference -d 'affect the referent of each symbolic link (this is the default), rather than …'
complete -c gchown -s h -l no-dereference -d 'affect symbolic links instead of any referenced file (useful only on systems …'
complete -c gchown -l from -d 'change the owner and/or group of each file only if its current owner and/or g…'
complete -c gchown -l no-preserve-root -d 'do not treat \'/\' specially (the default)'
complete -c gchown -l preserve-root -d 'fail to operate recursively on \'/\''
complete -c gchown -l reference -d 'use RFILE\'s owner and group rather than specifying OWNER:GROUP values'
complete -c gchown -s R -l recursive -d 'operate on files and directories recursively '
complete -c gchown -s H -d 'if a command line argument is a symbolic link to a directory, traverse it'
complete -c gchown -s L -d 'traverse every symbolic link to a directory encountered'
complete -c gchown -s P -d 'do not traverse any symbolic links (default)'
complete -c gchown -l help -d 'display this help and exit'
complete -c gchown -l version -d 'output version information and exit'

