# gchroot
# Autogenerated from man page /usr/local/share/man/man1/gchroot.1
complete -c gchroot -l groups -d 'specify supplementary groups as g1,g2,. ,gN'
complete -c gchroot -l userspec -d 'specify user and group (ID or name) to use'
complete -c gchroot -l skip-chdir -d 'do not change working directory to \'/\''
complete -c gchroot -l help -d 'display this help and exit'
complete -c gchroot -l version -d 'output version information and exit'

