# gcomm
# Autogenerated from man page /usr/local/share/man/man1/gcomm.1
complete -c gcomm -s 1 -d 'suppress column 1 (lines unique to FILE1)'
complete -c gcomm -s 2 -d 'suppress column 2 (lines unique to FILE2)'
complete -c gcomm -s 3 -d 'suppress column 3 (lines that appear in both files)'
complete -c gcomm -l check-order -d 'check that the input is correctly sorted, even if all input lines are pairable'
complete -c gcomm -l nocheck-order -d 'do not check that the input is correctly sorted'
complete -c gcomm -l output-delimiter -d 'separate columns with STR'
complete -c gcomm -l total -d 'output a summary'
complete -c gcomm -s z -l zero-terminated -d 'line delimiter is NUL, not newline'
complete -c gcomm -l help -d 'display this help and exit'
complete -c gcomm -l version -d 'output version information and exit'

