# gcsplit
# Autogenerated from man page /usr/local/share/man/man1/gcsplit.1
complete -c gcsplit -s b -l suffix-format -d 'use sprintf FORMAT instead of %02d'
complete -c gcsplit -s f -l prefix -d 'use PREFIX instead of \'xx\''
complete -c gcsplit -s k -l keep-files -d 'do not remove output files on errors'
complete -c gcsplit -l suppress-matched -d 'suppress the lines matching PATTERN'
complete -c gcsplit -s n -l digits -d 'use specified number of digits instead of 2'
complete -c gcsplit -s s -l quiet -l silent -d 'do not print counts of output file sizes'
complete -c gcsplit -s z -l elide-empty-files -d 'remove empty output files'
complete -c gcsplit -l help -d 'display this help and exit'
complete -c gcsplit -l version -d 'output version information and exit . SS "Each PATTERN may be:"'

