# gcut
# Autogenerated from man page /usr/local/share/man/man1/gcut.1
complete -c gcut -s b -l bytes -d 'select only these bytes'
complete -c gcut -s c -l characters -d 'select only these characters'
complete -c gcut -s d -l delimiter -d 'use DELIM instead of TAB for field delimiter'
complete -c gcut -s f -l fields -d 'select only these fields;  also print any line that contains no delimiter cha…'
complete -c gcut -s n -d '(ignored)'
complete -c gcut -l complement -d 'complement the set of selected bytes, characters or fields'
complete -c gcut -s s -l only-delimited -d 'do not print lines not containing delimiters'
complete -c gcut -l output-delimiter -d 'use STRING as the output delimiter the default is to use the input delimiter'
complete -c gcut -s z -l zero-terminated -d 'line delimiter is NUL, not newline'
complete -c gcut -l help -d 'display this help and exit'
complete -c gcut -l version -d 'output version information and exit '
complete -c gcut -s M -d 'from first to M\'th (included) byte, character or field AUTHOR Written by Davi…'

