# gdate
# Autogenerated from man page /usr/local/share/man/man1/gdate.1
complete -c gdate -s d -l date -d 'display time described by STRING, not \'now\''
complete -c gdate -l debug -d 'annotate the parsed date, and warn about questionable usage to stderr'
complete -c gdate -s f -l file -d 'like --date; once for each line of DATEFILE'
complete -c gdate -s I -l iso-8601 -d 'output date/time in ISO 8601 format'
complete -c gdate -s R -l rfc-email -d 'output date and time in RFC 5322 format'
complete -c gdate -l rfc-3339 -d 'output date/time in RFC 3339 format'
complete -c gdate -s r -l reference -d 'display the last modification time of FILE'
complete -c gdate -s s -l set -d 'set time described by STRING'
complete -c gdate -s u -l utc -l universal -d 'print or set Coordinated Universal Time (UTC)'
complete -c gdate -l help -d 'display this help and exit'
complete -c gdate -l version -d 'output version information and exit . PP FORMAT controls the output'

