# gdd
# Autogenerated from man page /usr/local/share/man/man1/gdd.1
complete -c gdd -l help -d 'display this help and exit'
complete -c gdd -l version -d 'output version information and exit AUTHOR Written by Paul Rubin, David MacKe…'

