# gdircolors
# Autogenerated from man page /usr/local/share/man/man1/gdircolors.1
complete -c gdircolors -s b -l sh -l bourne-shell -d 'output Bourne shell code to set LS_COLORS'
complete -c gdircolors -s c -l csh -l c-shell -d 'output C shell code to set LS_COLORS'
complete -c gdircolors -s p -l print-database -d 'output defaults'
complete -c gdircolors -l help -d 'display this help and exit'
complete -c gdircolors -l version -d 'output version information and exit'

