# gdirname
# Autogenerated from man page /usr/local/share/man/man1/gdirname.1
complete -c gdirname -s z -l zero -d 'end each output line with NUL, not newline'
complete -c gdirname -l help -d 'display this help and exit'
complete -c gdirname -l version -d 'output version information and exit EXAMPLES'
complete -c gdirname -s '>'

