# gecho
# Autogenerated from man page /usr/local/share/man/man1/gecho.1
complete -c gecho -s n -d 'do not output the trailing newline'
complete -c gecho -s e -d 'enable interpretation of backslash escapes'
complete -c gecho -s E -d 'disable interpretation of backslash escapes (default)'
complete -c gecho -l help -d 'display this help and exit'
complete -c gecho -l version -d 'output version information and exit '

