# genv
# Autogenerated from man page /usr/local/share/man/man1/genv.1
complete -c genv -s i -l ignore-environment -d 'start with an empty environment'
complete -c genv -s 0 -l null -d 'end each output line with NUL, not newline'
complete -c genv -s u -l unset -d 'remove variable from the environment'
complete -c genv -s C -l chdir -d 'change working directory to DIR'
complete -c genv -s S -l split-string -d 'process and split S into separate arguments; used to pass multiple arguments …'
complete -c genv -l block-signal -d 'block delivery of SIG signal(s) to COMMAND'
complete -c genv -l default-signal -d 'reset handling of SIG signal(s) to the default'
complete -c genv -l ignore-signal -d 'set handling of SIG signals(s) to do nothing'
complete -c genv -l list-signal-handling -d 'list non default signal handling to stderr'
complete -c genv -s v -l debug -d 'print verbose information for each processing step'
complete -c genv -l help -d 'display this help and exit'
complete -c genv -l version -d 'output version information and exit'
complete -c genv -o S/--split-string -d The

