# geoiplookup6
# Autogenerated from man page /usr/local/share/man/man1/geoiplookup6.1
complete -c geoiplookup6 -s f -d 'Specify a custom path to a single GeoIP datafile'
complete -c geoiplookup6 -s d -d 'Specify a custom directory containing GeoIP datafile(s)'
complete -c geoiplookup6 -s v -d 'Lists the date and build number for the GeoIP datafile(s)'

