# gexpr
# Autogenerated from man page /usr/local/share/man/man1/gexpr.1
complete -c gexpr -l help -d 'display this help and exit'
complete -c gexpr -l version -d 'output version information and exit '

