# gexpand
# Autogenerated from man page /usr/local/share/man/man1/gexpand.1
complete -c gexpand -s i -l initial -d 'do not convert tabs after non blanks'
complete -c gexpand -s t -l tabs -d 'have tabs N characters apart, not 8'
complete -c gexpand -l help -d 'display this help and exit'
complete -c gexpand -l version -d 'output version information and exit AUTHOR Written by David MacKenzie'

