# gfalse
# Autogenerated from man page /usr/local/share/man/man1/gfalse.1
complete -c gfalse -l help -d 'display this help and exit'
complete -c gfalse -l version -d 'output version information and exit'

