# gfmt
# Autogenerated from man page /usr/local/share/man/man1/gfmt.1
complete -c gfmt -s c -l crown-margin -d 'preserve indentation of first two lines'
complete -c gfmt -s p -l prefix -d 'reformat only lines beginning with STRING, reattaching the prefix to reformat…'
complete -c gfmt -s s -l split-only -d 'split long lines, but do not refill'
complete -c gfmt -s t -l tagged-paragraph -d 'indentation of first line different from second'
complete -c gfmt -s u -l uniform-spacing -d 'one space between words, two after sentences'
complete -c gfmt -s w -l width -d 'maximum line width (default of 75 columns)'
complete -c gfmt -s g -l goal -d 'goal width (default of 93% of width)'
complete -c gfmt -l help -d 'display this help and exit'
complete -c gfmt -l version -d 'output version information and exit AUTHOR Written by Ross Paterson'

