# gfold
# Autogenerated from man page /usr/local/share/man/man1/gfold.1
complete -c gfold -s b -l bytes -d 'count bytes rather than columns'
complete -c gfold -s s -l spaces -d 'break at spaces'
complete -c gfold -s w -l width -d 'use WIDTH columns instead of 80'
complete -c gfold -l help -d 'display this help and exit'
complete -c gfold -l version -d 'output version information and exit AUTHOR Written by David MacKenzie'

