# ggroups
# Autogenerated from man page /usr/local/share/man/man1/ggroups.1
complete -c ggroups -l help -d 'display this help and exit'
complete -c ggroups -l version -d 'output version information and exit AUTHOR Written by David MacKenzie and Jam…'

