# ghead
# Autogenerated from man page /usr/local/share/man/man1/ghead.1
complete -c ghead -s c -l bytes -d 'print the first NUM bytes of each file; with the leading \'-\', print all but t…'
complete -c ghead -s n -l lines -d 'print the first NUM lines instead of the first 10; with the leading \'-\', prin…'
complete -c ghead -s q -l quiet -l silent -d 'never print headers giving file names'
complete -c ghead -s v -l verbose -d 'always print headers giving file names'
complete -c ghead -s z -l zero-terminated -d 'line delimiter is NUL, not newline'
complete -c ghead -l help -d 'display this help and exit'
complete -c ghead -l version -d 'output version information and exit'

