# gid
# Autogenerated from man page /usr/local/share/man/man1/gid.1
complete -c gid -s a -d 'ignore, for compatibility with other versions'
complete -c gid -s Z -l context -d 'print only the security context of the process'
complete -c gid -s g -l group -d 'print only the effective group ID'
complete -c gid -s G -l groups -d 'print all group IDs'
complete -c gid -s n -l name -d 'print a name instead of a number, for -ugG'
complete -c gid -s r -l real -d 'print the real ID instead of the effective ID, with -ugG'
complete -c gid -s u -l user -d 'print only the effective user ID'
complete -c gid -s z -l zero -d 'delimit entries with NUL characters, not whitespace; P not permitted in defau…'
complete -c gid -l help -d 'display this help and exit'
complete -c gid -l version -d 'output version information and exit'

