# git-commit-graph
# Autogenerated from man page /usr/local/share/man/man1/git-commit-graph.1
complete -c git-commit-graph -l changed-paths -d 'option, compute and write information about the paths changed between a commi…'
complete -c git-commit-graph -l no-changed-paths -d 'to stop storing this data'
complete -c git-commit-graph -l max-new-filters -d 'option, generate at most n new Bloom filters (if'
complete -c git-commit-graph -s 1

