# git-format-patch
# Autogenerated from man page /usr/local/share/man/man1/git-format-patch.1
complete -c git-format-patch -l relative -l no-relative -d 'When run from a subdirectory of the project, it can be told to exclude change…'
complete -c git-format-patch -o 'I<regex>' -l ignore-matching-lines -d 'Ignore changes whose all lines match <regex>'
complete -c git-format-patch -l cover-from-description -d 'Controls which parts of the cover letter will be automatically populated usin…'
complete -c git-format-patch -l filename-max-length -d 'Instead of the standard 64 bytes, chomp the generated output filenames at aro…'
complete -c git-format-patch -l encode-email-headers -l no-encode-email-headers -d 'Encode email headers that have non-ASCII characters with "Q-encoding" (descri…'
complete -c git-format-patch -l no-base -d 'option overrides a format. useAutoBase configuration'

