# git-stash
# Autogenerated from man page /usr/local/share/man/man1/git-stash.1
complete -c git-stash -l pathspec-from-file -d 'This option is only valid for push command'
complete -c git-stash -l pathspec-file-nul -d 'This option is only valid for push command'
complete -c git-stash -l literal-pathspecs

