# git-config
# Autogenerated from man page /usr/local/share/man/man1/git-config.1
complete -c git-config -l fixed-value -d 'When used with the value-pattern argument, treat value-pattern as an exact st…'
complete -c git-config -l show-scope -d 'Similar to --show-origin in that it augments the output of all queried config…'
complete -c git-config -l guess -d or
complete -c git-config -l no-guess -d 'option in git checkout and git switch.  See git-switch(1) and git-checkout(1)'
complete -c git-config -l origin -d 'command-line option to git-clone(1).  color. advice'
complete -c git-config -l max-new-filters -d 'option of git commit-graph write (c. f. , git-commit-graph(1)).  commitGraph'
complete -c git-config -l cover-from-description -d 'option in git-format-patch(1).  format. signature'
complete -c git-config -l filename-max-length -d 'command line option.  format. useAutoBase'
complete -c git-config -l keep-largest-pack -d 'except that all packs that meet the threshold are kept, not just the largest …'
complete -c git-config -l decorate-refs-exclude -d 'command-line option, but the config option can be overridden by the'
complete -c git-config -l decorate-refs -d 'option.  log. follow'
complete -c git-config -l task -d 'arguments are provided.  Further, if a maintenance. <task>'
complete -c git-config -l auto -d 'option.  A negative value will force the task to run every time'
complete -c git-config -l auto-merge -d 'is given, meld will merge all non-conflicting parts automatically, highlight …'
complete -c git-config -l force-if-includes -d 'as an option to git-push(1) in the command line.  Adding'
complete -c git-config -l no-force-if-includes -d 'at the time of push overrides this configuration setting.  rebase. useBuiltin'
complete -c git-config -l no-recurse-submodules -d option
complete -c git-config -l filter -d 'when <n> is no more than the value of uploadpackfilter. tree. maxDepth'

