# git-diff-index
# Autogenerated from man page /usr/local/share/man/man1/git-diff-index.1
complete -c git-diff-index -l no-relative -d 'When run from a subdirectory of the project, it can be told to exclude change…'
complete -c git-diff-index -o 'I<regex>' -l ignore-matching-lines -d 'Ignore changes whose all lines match <regex>'
complete -c git-diff-index -l merge-base -d 'Instead of comparing <tree-ish> directly, use the merge base between <tree-is…'

