# git-commit
# Autogenerated from man page /usr/local/share/man/man1/git-commit.1
complete -c git-commit -l no-signoff -d 'Add a Signed-off-by trailer by the committer at the end of the commit log mes…'
complete -c git-commit -l pathspec-from-file -d 'Pathspec is passed in <file> instead of commandline args'
complete -c git-commit -l pathspec-file-nul -d 'Only meaningful with --pathspec-from-file'
complete -c git-commit -l literal-pathspecs

