# git-log
# Autogenerated from man page /usr/local/share/man/man1/git-log.1
complete -c git-log -l mailmap -d 'Use mailmap file to map author and committer names and email addresses to can…'
complete -c git-log -o 'L<start>' -o 'L:<funcname>:<file>' -d 'Trace the evolution of the line range given by <start>,<end>, or by the funct…'
complete -c git-log -l show-pulls -d 'Include all commits from the default mode, but also any merge commits that ar…'
complete -c git-log -l diff-merges -l no-diff-merges
complete -c git-log -l no-relative
complete -c git-log -o 'I<regex>' -l ignore-matching-lines

