# git-rev-list
# Autogenerated from man page /usr/local/share/man/man1/git-rev-list.1
complete -c git-rev-list -l show-pulls -d 'Include all commits from the default mode, but also any merge commits that ar…'
complete -c git-rev-list -l decorate -d and

