# git-fast-import
# Autogenerated from man page /usr/local/share/man/man1/git-fast-import.1
complete -c git-fast-import -l allow-unsafe-features -d 'Many command-line options can be provided as part of the fast-import stream i…'
complete -c git-fast-import -l rewrite-submodules-from -l rewrite-submodules-to -d 'Rewrite the object IDs for the submodule specified by <name> from the values …'

