# git-range-diff
# Autogenerated from man page /usr/local/share/man/man1/git-range-diff.1
complete -c git-range-diff -l notes -d 'This flag is passed to the git log program (see git-log(1)) that generates th…'

