# git-diff
# Autogenerated from man page /usr/local/share/man/man1/git-diff.1
complete -c git-diff -l no-relative -d 'When run from a subdirectory of the project, it can be told to exclude change…'
complete -c git-diff -o 'I<regex>' -l ignore-matching-lines -d 'Ignore changes whose all lines match <regex>'

