# git-merge
# Autogenerated from man page /usr/local/share/man/man1/git-merge.1
complete -c git-merge -l no-gpg-sign -d 'GPG-sign the resulting merge commit'
complete -c git-merge -l autostash -l no-autostash -d 'Automatically create a temporary stash entry before the operation begins, and…'

