# git-http-fetch
# Autogenerated from man page /usr/local/share/man/man1/git-http-fetch.1
complete -c git-http-fetch -l packfile -d 'Instead of a commit id on the command line (which is not expected in this cas…'

