# git-checkout
# Autogenerated from man page /usr/local/share/man/man1/git-checkout.1
complete -c git-checkout -s d -d 'Rather than checking out a branch to work on it, check out a commit for inspe…'
complete -c git-checkout -l pathspec-from-file -d 'Pathspec is passed in <file> instead of commandline args'
complete -c git-checkout -l pathspec-file-nul -d 'Only meaningful with --pathspec-from-file'
complete -c git-checkout -l literal-pathspecs

