# git-archive
# Autogenerated from man page /usr/local/share/man/man1/git-archive.1
complete -c git-archive -l add-file -d 'Add a non-tracked file to the archive.  Can be repeated to add multiple files'

