# git-update-index
# Autogenerated from man page /usr/local/share/man/man1/git-update-index.1
complete -c git-update-index -l ignore-skip-worktree-entries -d 'Do not remove skip-worktree (AKA "index-only") entries even when the --remove…'

