# git-rm
# Autogenerated from man page /usr/local/share/man/man1/git-rm.1
complete -c git-rm -l pathspec-from-file -d 'Pathspec is passed in <file> instead of commandline args'
complete -c git-rm -l pathspec-file-nul -d 'Only meaningful with --pathspec-from-file'
complete -c git-rm -l literal-pathspecs

