# git-clone
# Autogenerated from man page /usr/local/share/man/man1/git-clone.1
complete -c git-clone -l sparse -d 'Initialize the sparse-checkout file so the working directory starts with only…'
complete -c git-clone -l filter -d 'Use the partial clone feature and request that the server sends a subset of r…'

