# git-init
# Autogenerated from man page /usr/local/share/man/man1/git-init.1
complete -c git-init -l object-format -d 'Specify the given object format (hash algorithm) for the repository'
complete -c git-init -s b -l initial-branch -d 'Use the specified name for the initial branch in the newly created repository'

