# git-show
# Autogenerated from man page /usr/local/share/man/man1/git-show.1
complete -c git-show -l date -d 'unless another'
complete -c git-show -l decorate -d and
complete -c git-show -l walk-reflogs -d 'oc o 2. 3'
complete -c git-show -l no-relative
complete -c git-show -o 'I<regex>' -l ignore-matching-lines

