# git-push
# Autogenerated from man page /usr/local/share/man/man1/git-push.1
complete -c git-push -l force-if-includes -d 'Force an update only if the tip of the remote-tracking ref has been integrate…'
complete -c git-push -l no-force-if-includes -d 'disables this behavior'

