# git-pull
# Autogenerated from man page /usr/local/share/man/man1/git-pull.1
complete -c git-pull -l no-gpg-sign -d 'GPG-sign the resulting merge commit'
complete -c git-pull -l dry-run -d 'Show what would be done, without making any changes'
complete -c git-pull -s p -l prune -d 'Before fetching, remove any remote-tracking references that no longer exist o…'
complete -c git-pull -l refmap -d 'When fetching refs listed on the command line, use the specified refspec (can…'
complete -c git-pull -s t -l tags -d 'Fetch all tags from the remote (i. e'
complete -c git-pull -s j -l jobs -d 'Number of parallel children to be used for all forms of fetching'
complete -c git-pull -l set-upstream -d 'If the remote is fetched successfully, add upstream (tracking) reference, use…'
complete -c git-pull -l prune-tags -d 'is a shorthand for providing the tag refspec'
complete -c git-pull -l multiple -d 'option was specified, the different remotes will be fetched in parallel'

