# git-diff-tree
# Autogenerated from man page /usr/local/share/man/man1/git-diff-tree.1
complete -c git-diff-tree -l no-relative -d 'When run from a subdirectory of the project, it can be told to exclude change…'
complete -c git-diff-tree -o 'I<regex>' -l ignore-matching-lines -d 'Ignore changes whose all lines match <regex>'
complete -c git-diff-tree -l merge-base -d 'Instead of comparing the <tree-ish>s directly, use the merge base between the…'
complete -c git-diff-tree -l date -d 'unless another'
complete -c git-diff-tree -l decorate -d and
complete -c git-diff-tree -l walk-reflogs -d 'oc o 2. 3'

