# git-add
# Autogenerated from man page /usr/local/share/man/man1/git-add.1
complete -c git-add -l pathspec-from-file -d 'Pathspec is passed in <file> instead of commandline args'
complete -c git-add -l pathspec-file-nul -d 'Only meaningful with --pathspec-from-file'
complete -c git-add -l literal-pathspecs

