# git-diff-files
# Autogenerated from man page /usr/local/share/man/man1/git-diff-files.1
complete -c git-diff-files -l no-relative -d 'When run from a subdirectory of the project, it can be told to exclude change…'
complete -c git-diff-files -o 'I<regex>' -l ignore-matching-lines -d 'Ignore changes whose all lines match <regex>'

