# git-reset
# Autogenerated from man page /usr/local/share/man/man1/git-reset.1
complete -c git-reset -l pathspec-from-file -d 'Pathspec is passed in <file> instead of commandline args'
complete -c git-reset -l pathspec-file-nul -d 'Only meaningful with --pathspec-from-file'
complete -c git-reset -l recurse-submodules
complete -c git-reset -l literal-pathspecs

