# git-fetch
# Autogenerated from man page /usr/local/share/man/man1/git-fetch.1
complete -c git-fetch -l write-fetch-head -d 'Write the list of remote refs fetched in the FETCH_HEAD file directly under $…'
complete -c git-fetch -l auto-maintenance -d 'Run git maintenance run --auto at the end to perform automatic repository mai…'
complete -c git-fetch -l write-commit-graph -d 'Write a commit-graph after fetching.  This overrides the config setting fetch'
complete -c git-fetch -l stdin -d 'Read refspecs, one per line, from stdin in addition to those provided as argu…'
complete -c git-fetch -l no-write-fetch-head -d 'from the command line tells Git not to write the file.  Under'

