# git-rev-parse
# Autogenerated from man page /usr/local/share/man/man1/git-rev-parse.1
complete -c git-rev-parse -l show-object-format -d 'Show the object format (hash algorithm) used for the repository for storage i…'
complete -c git-rev-parse -l end-of-options -d 'so that the name argument is not mistaken for another option'

