# git-rebase
# Autogenerated from man page /usr/local/share/man/man1/git-rebase.1
complete -c git-rebase -l apply -d 'Use applying strategies to rebase (calling git-am internally)'
complete -c git-rebase -l empty -d 'How to handle commits that are not empty to start and are not clean cherry-pi…'
complete -c git-rebase -l no-keep-empty -d 'Do not keep commits that start empty before the rebase (i. e'
complete -c git-rebase -l reapply-cherry-picks -l no-reapply-cherry-picks -d 'Reapply all clean cherry-picks of any upstream commit instead of preemptively…'
complete -c git-rebase -l no-gpg-sign -d 'GPG-sign commits'
complete -c git-rebase -l reset-author-date -d 'Instead of using the author date of the original commit, use the current time…'

