# gjoin
# Autogenerated from man page /usr/local/share/man/man1/gjoin.1
complete -c gjoin -s a -d 'also print unpairable lines from file FILENUM, where FILENUM is 1 or 2, corre…'
complete -c gjoin -s e -d 'replace missing input fields with EMPTY'
complete -c gjoin -s i -l ignore-case -d 'ignore differences in case when comparing fields'
complete -c gjoin -s j -d 'equivalent to \'-1 FIELD -2 FIELD\''
complete -c gjoin -s o -d 'obey FORMAT while constructing output line'
complete -c gjoin -s t -d 'use CHAR as input and output field separator'
complete -c gjoin -s v -d 'like -a FILENUM, but suppress joined output lines'
complete -c gjoin -s 1 -d 'join on this FIELD of file 1'
complete -c gjoin -s 2 -d 'join on this FIELD of file 2'
complete -c gjoin -l check-order -d 'check that the input is correctly sorted, even if all input lines are pairable'
complete -c gjoin -l nocheck-order -d 'do not check that the input is correctly sorted'
complete -c gjoin -l header -d 'treat the first line in each file as field headers, print them without trying…'
complete -c gjoin -s z -l zero-terminated -d 'line delimiter is NUL, not newline'
complete -c gjoin -l help -d 'display this help and exit'
complete -c gjoin -l version -d 'output version information and exit'

