# glogname
# Autogenerated from man page /usr/local/share/man/man1/glogname.1
complete -c glogname -l help -d 'display this help and exit'
complete -c glogname -l version -d 'output version information and exit AUTHOR Written by FIXME: unknown'

