# gmkdir
# Autogenerated from man page /usr/local/share/man/man1/gmkdir.1
complete -c gmkdir -s m -l mode -d 'set file mode (as in chmod), not a=rwx - umask'
complete -c gmkdir -s p -l parents -d 'no error if existing, make parent directories as needed'
complete -c gmkdir -s v -l verbose -d 'print a message for each created directory'
complete -c gmkdir -s Z -d 'set SELinux security context of each created directory to the default type'
complete -c gmkdir -l context -d 'like -Z, or if CTX is specified then set the SELinux or SMACK security contex…'
complete -c gmkdir -l help -d 'display this help and exit'
complete -c gmkdir -l version -d 'output version information and exit AUTHOR Written by David MacKenzie'

