# gmkfifo
# Autogenerated from man page /usr/local/share/man/man1/gmkfifo.1
complete -c gmkfifo -s m -l mode -d 'set file permission bits to MODE, not a=rw - umask'
complete -c gmkfifo -s Z -d 'set the SELinux security context to default type'
complete -c gmkfifo -l context -d 'like -Z, or if CTX is specified then set the SELinux or SMACK security contex…'
complete -c gmkfifo -l help -d 'display this help and exit'
complete -c gmkfifo -l version -d 'output version information and exit AUTHOR Written by David MacKenzie'

