# gmknod
# Autogenerated from man page /usr/local/share/man/man1/gmknod.1
complete -c gmknod -s m -l mode -d 'set file permission bits to MODE, not a=rw - umask'
complete -c gmknod -s Z -d 'set the SELinux security context to default type'
complete -c gmknod -l context -d 'like -Z, or if CTX is specified then set the SELinux or SMACK security contex…'
complete -c gmknod -l help -d 'display this help and exit'
complete -c gmknod -l version -d 'output version information and exit '

