# gmktemp
# Autogenerated from man page /usr/local/share/man/man1/gmktemp.1
complete -c gmktemp -s d -l directory -d 'create a directory, not a file'
complete -c gmktemp -s u -l dry-run -d 'do not create anything; merely print a name (unsafe)'
complete -c gmktemp -s q -l quiet -d 'suppress diagnostics about file/dir-creation failure'
complete -c gmktemp -l suffix -d 'append SUFF to TEMPLATE; SUFF must not contain a slash'
complete -c gmktemp -s p -l tmpdir -d 'interpret TEMPLATE relative to DIR; if DIR is not specified, use $TMPDIR if s…'
complete -c gmktemp -s t -d 'interpret TEMPLATE as a single file name component, relative to a directory: …'
complete -c gmktemp -l help -d 'display this help and exit'
complete -c gmktemp -l version -d 'output version information and exit AUTHOR Written by Jim Meyering and Eric B…'

