# gmv
# Autogenerated from man page /usr/local/share/man/man1/gmv.1
complete -c gmv -l backup -d 'make a backup of each existing destination file'
complete -c gmv -s b -d 'like --backup but does not accept an argument'
complete -c gmv -s f -l force -d 'do not prompt before overwriting'
complete -c gmv -s i -l interactive -d 'prompt before overwrite'
complete -c gmv -s n -l no-clobber -d 'do not overwrite an existing file '
complete -c gmv -l strip-trailing-slashes -d 'remove any trailing slashes from each SOURCE argument'
complete -c gmv -s S -l suffix -d 'override the usual backup suffix'
complete -c gmv -s t -l target-directory -d 'move all SOURCE arguments into DIRECTORY'
complete -c gmv -s T -l no-target-directory -d 'treat DEST as a normal file'
complete -c gmv -s u -l update -d 'move only when the SOURCE file is newer than the destination file or when the…'
complete -c gmv -s v -l verbose -d 'explain what is being done'
complete -c gmv -s Z -l context -d 'set SELinux security context of destination file to default type'
complete -c gmv -l help -d 'display this help and exit'
complete -c gmv -l version -d 'output version information and exit '

