# gnice
# Autogenerated from man page /usr/local/share/man/man1/gnice.1
complete -c gnice -s n -l adjustment -d 'add integer N to the niceness (default 10)'
complete -c gnice -l help -d 'display this help and exit'
complete -c gnice -o 20
complete -c gnice -l version -d 'output version information and exit'

