# gnohup
# Autogenerated from man page /usr/local/share/man/man1/gnohup.1
complete -c gnohup -l help -d 'display this help and exit'
complete -c gnohup -l version -d 'output version information and exit'

