# gnproc
# Autogenerated from man page /usr/local/share/man/man1/gnproc.1
complete -c gnproc -l all -d 'print the number of installed processors'
complete -c gnproc -l ignore -d 'if possible, exclude N processing units'
complete -c gnproc -l help -d 'display this help and exit'
complete -c gnproc -l version -d 'output version information and exit AUTHOR Written by Giuseppe Scrivano'

