# gpaste
# Autogenerated from man page /usr/local/share/man/man1/gpaste.1
complete -c gpaste -s d -l delimiters -d 'reuse characters from LIST instead of TABs'
complete -c gpaste -s s -l serial -d 'paste one file at a time instead of in parallel'
complete -c gpaste -s z -l zero-terminated -d 'line delimiter is NUL, not newline'
complete -c gpaste -l help -d 'display this help and exit'
complete -c gpaste -l version -d 'output version information and exit AUTHOR Written by David M'

