# gpathchk
# Autogenerated from man page /usr/local/share/man/man1/gpathchk.1
complete -c gpathchk -s p -d 'check for most POSIX systems'
complete -c gpathchk -s P -d 'check for empty names and leading "-"'
complete -c gpathchk -l portability -d 'check for all POSIX systems (equivalent to -p -P)'
complete -c gpathchk -l help -d 'display this help and exit'
complete -c gpathchk -l version -d 'output version information and exit AUTHOR Written by Paul Eggert, David MacK…'

