# gpinky
# Autogenerated from man page /usr/local/share/man/man1/gpinky.1
complete -c gpinky -s l -d 'produce long format output for the specified USERs'
complete -c gpinky -s b -d 'omit the user\'s home directory and shell in long format'
complete -c gpinky -s h -d 'omit the user\'s project file in long format'
complete -c gpinky -s p -d 'omit the user\'s plan file in long format'
complete -c gpinky -s s -d 'do short format output, this is the default'
complete -c gpinky -s f -d 'omit the line of column headings in short format'
complete -c gpinky -s w -d 'omit the user\'s full name in short format'
complete -c gpinky -s i -d 'omit the user\'s full name and remote host in short format'
complete -c gpinky -s q -d 'omit the user\'s full name, remote host and idle time in short format'
complete -c gpinky -l help -d 'display this help and exit'
complete -c gpinky -l version -d 'output version information and exit'

