# gprintf
# Autogenerated from man page /usr/local/share/man/man1/gprintf.1
complete -c gprintf -l help -d 'display this help and exit'
complete -c gprintf -l version -d 'output version information and exit '

