# gprintenv
# Autogenerated from man page /usr/local/share/man/man1/gprintenv.1
complete -c gprintenv -s 0 -l null -d 'end each output line with NUL, not newline'
complete -c gprintenv -l help -d 'display this help and exit'
complete -c gprintenv -l version -d 'output version information and exit'

