# gptx
# Autogenerated from man page /usr/local/share/man/man1/gptx.1
complete -c gptx -s A -l auto-reference -d 'output automatically generated references'
complete -c gptx -s G -l traditional -d 'behave more like System V \'ptx\''
complete -c gptx -s F -l flag-truncation -d 'use STRING for flagging line truncations.  The default is \'/\''
complete -c gptx -s M -l macro-name -d 'macro name to use instead of \'xx\''
complete -c gptx -s O -l format -d 'generate output as roff directives'
complete -c gptx -s R -l right-side-refs -d 'put references at right, not counted in -w'
complete -c gptx -s S -l sentence-regexp -d 'for end of lines or end of sentences'
complete -c gptx -s T -d 'generate output as TeX directives'
complete -c gptx -s W -l word-regexp -d 'use REGEXP to match each keyword'
complete -c gptx -s b -l break-file -d 'word break characters in this FILE'
complete -c gptx -s f -l ignore-case -d 'fold lower case to upper case for sorting'
complete -c gptx -s g -l gap-size -d 'gap size in columns between output fields'
complete -c gptx -s i -l ignore-file -d 'read ignore word list from FILE'
complete -c gptx -s o -l only-file -d 'read only word list from this FILE'
complete -c gptx -s r -l references -d 'first field of each line is a reference '
complete -c gptx -s w -l width -d 'output width in columns, reference excluded'
complete -c gptx -l help -d 'display this help and exit'
complete -c gptx -s t -l typeset-mode
complete -c gptx -l version -d 'output version information and exit AUTHOR Written by Francois Pinard'

