# gpwd
# Autogenerated from man page /usr/local/share/man/man1/gpwd.1
complete -c gpwd -s L -l logical -d 'use PWD from environment, even if it contains symlinks'
complete -c gpwd -s P -l physical -d 'avoid all symlinks'
complete -c gpwd -l help -d 'display this help and exit'
complete -c gpwd -l version -d 'output version information and exit'

