# grealpath
# Autogenerated from man page /usr/local/share/man/man1/grealpath.1
complete -c grealpath -s e -l canonicalize-existing -d 'all components of the path must exist'
complete -c grealpath -s m -l canonicalize-missing -d 'no path components need exist or be a directory'
complete -c grealpath -s L -l logical -d 'resolve \'. \' components before symlinks'
complete -c grealpath -s P -l physical -d 'resolve symlinks as encountered (default)'
complete -c grealpath -s q -l quiet -d 'suppress most error messages'
complete -c grealpath -l relative-to -d 'print the resolved path relative to DIR'
complete -c grealpath -l relative-base -d 'print absolute paths unless paths below DIR'
complete -c grealpath -s s -l strip -l no-symlinks -d 'don\'t expand symlinks'
complete -c grealpath -s z -l zero -d 'end each output line with NUL, not newline'
complete -c grealpath -l help -d 'display this help and exit'
complete -c grealpath -l version -d 'output version information and exit AUTHOR Written by Padraig Brady'

