# greadlink
# Autogenerated from man page /usr/local/share/man/man1/greadlink.1
complete -c greadlink -s f -l canonicalize -d 'canonicalize by following every symlink in every component of the given name …'
complete -c greadlink -s e -l canonicalize-existing -d 'canonicalize by following every symlink in every component of the given name …'
complete -c greadlink -s m -l canonicalize-missing -d 'canonicalize by following every symlink in every component of the given name …'
complete -c greadlink -s n -l no-newline -d 'do not output the trailing delimiter . HP -q, --quiet'
complete -c greadlink -s s -l silent -d 'suppress most error messages (on by default)'
complete -c greadlink -s v -l verbose -d 'report error messages'
complete -c greadlink -s z -l zero -d 'end each output line with NUL, not newline'
complete -c greadlink -l help -d 'display this help and exit'
complete -c greadlink -s q -l quiet
complete -c greadlink -l version -d 'output version information and exit AUTHOR Written by Dmitry V.  Levin'

