# grm
# Autogenerated from man page /usr/local/share/man/man1/grm.1
complete -c grm -s f -l force -d 'ignore nonexistent files and arguments, never prompt'
complete -c grm -s i -d 'prompt before every removal'
complete -c grm -s I -d 'prompt once before removing more than three files, or when removing recursive…'
complete -c grm -l interactive -d 'prompt according to WHEN: never, once (-I), or always (-i); without WHEN, pro…'
complete -c grm -l one-file-system -d 'when removing a hierarchy recursively, skip any directory that is on a file s…'
complete -c grm -l no-preserve-root -d 'do not treat \'/\' specially'
complete -c grm -l preserve-root -d 'do not remove \'/\' (default); with \'all\', reject any command line argument on …'
complete -c grm -s r -s R -l recursive -d 'remove directories and their contents recursively'
complete -c grm -s d -l dir -d 'remove empty directories'
complete -c grm -s v -l verbose -d 'explain what is being done'
complete -c grm -l help -d 'display this help and exit'
complete -c grm -l version -d 'output version information and exit '

