# grmdir
# Autogenerated from man page /usr/local/share/man/man1/grmdir.1
complete -c grmdir -s p -l parents -d 'remove DIRECTORY and its ancestors; e. g'
complete -c grmdir -s v -l verbose -d 'output a diagnostic for every directory processed'
complete -c grmdir -l help -d 'display this help and exit'
complete -c grmdir -l ignore-fail-on-non-empty -d 'ignore each failure that is solely because a directory is non-empty'
complete -c grmdir -l version -d 'output version information and exit AUTHOR Written by David MacKenzie'

