# groffer
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/groffer.1
complete -c groffer -l shell
complete -c groffer -l foreground
complete -c groffer -l resolution
complete -c groffer -l x-viewer -o geometry -d '# # some shell commands if test "$DISPLAY" = ""; then   export DISPLAY=\'local…'

