# gruncon
# Autogenerated from man page /usr/local/share/man/man1/gruncon.1
complete -c gruncon -s c -l compute -d 'compute process transition context before modifying'
complete -c gruncon -s t -l type -d 'type (for same role as parent)'
complete -c gruncon -s u -l user -d 'user identity'
complete -c gruncon -s r -l role -d role
complete -c gruncon -s l -l range -d levelrange
complete -c gruncon -l help -d 'display this help and exit'
complete -c gruncon -l version -d 'output version information and exit AUTHOR Written by Russell Coker'

