# gseq
# Autogenerated from man page /usr/local/share/man/man1/gseq.1
complete -c gseq -s f -l format -d 'use printf style floating-point FORMAT'
complete -c gseq -s s -l separator -d 'use STRING to separate numbers (default: n)'
complete -c gseq -s w -l equal-width -d 'equalize width by padding with leading zeroes'
complete -c gseq -l help -d 'display this help and exit'
complete -c gseq -l version -d 'output version information and exit'

