# gsha256sum
# Autogenerated from man page /usr/local/share/man/man1/gsha256sum.1
complete -c gsha256sum -s b -l binary -d 'read in binary mode'
complete -c gsha256sum -s c -l check -d 'read SHA256 sums from the FILEs and check them'
complete -c gsha256sum -l tag -d 'create a BSD-style checksum'
complete -c gsha256sum -s t -l text -d 'read in text mode (default)'
complete -c gsha256sum -s z -l zero -d 'end each output line with NUL, not newline, and disable file name escaping '
complete -c gsha256sum -l ignore-missing -d 'don\'t fail or report status for missing files'
complete -c gsha256sum -l quiet -d 'don\'t print OK for each successfully verified file'
complete -c gsha256sum -l status -d 'don\'t output anything, status code shows success'
complete -c gsha256sum -l strict -d 'exit non-zero for improperly formatted checksum lines'
complete -c gsha256sum -s w -l warn -d 'warn about improperly formatted checksum lines'
complete -c gsha256sum -l help -d 'display this help and exit'
complete -c gsha256sum -l version -d 'output version information and exit'

