# gshred
# Autogenerated from man page /usr/local/share/man/man1/gshred.1
complete -c gshred -s f -l force -d 'change permissions to allow writing if necessary'
complete -c gshred -s n -l iterations -d 'overwrite N times instead of the default (3)'
complete -c gshred -l random-source -d 'get random bytes from FILE'
complete -c gshred -s s -l size -d 'shred this many bytes (suffixes like K, M, G accepted)'
complete -c gshred -s u -d 'deallocate and remove file after overwriting'
complete -c gshred -l remove -d 'like -u but give control on HOW to delete;  See below'
complete -c gshred -s v -l verbose -d 'show progress'
complete -c gshred -s x -l exact -d 'do not round file sizes up to the next full block; P this is the default for …'
complete -c gshred -s z -l zero -d 'add a final overwrite with zeros to hide shredding'
complete -c gshred -l help -d 'display this help and exit'
complete -c gshred -l version -d 'output version information and exit'

