# gshuf
# Autogenerated from man page /usr/local/share/man/man1/gshuf.1
complete -c gshuf -s e -l echo -d 'treat each ARG as an input line'
complete -c gshuf -s i -l input-range -d 'treat each number LO through HI as an input line'
complete -c gshuf -s n -l head-count -d 'output at most COUNT lines'
complete -c gshuf -s o -l output -d 'write result to FILE instead of standard output'
complete -c gshuf -l random-source -d 'get random bytes from FILE'
complete -c gshuf -s r -l repeat -d 'output lines can be repeated'
complete -c gshuf -s z -l zero-terminated -d 'line delimiter is NUL, not newline'
complete -c gshuf -l help -d 'display this help and exit'
complete -c gshuf -l version -d 'output version information and exit AUTHOR Written by Paul Eggert'

