# gstat
# Autogenerated from man page /usr/local/share/man/man1/gstat.1
complete -c gstat -s L -l dereference -d 'follow links'
complete -c gstat -s f -l file-system -d 'display file system status instead of file status'
complete -c gstat -l cached -d 'specify how to use cached attributes; useful on remote file systems'
complete -c gstat -s c -l format -d 'use the specified FORMAT instead of the default; output a newline after each …'
complete -c gstat -l printf -d 'like --format, but interpret backslash escapes, and do not output a mandatory…'
complete -c gstat -s t -l terse -d 'print the information in terse form'
complete -c gstat -l help -d 'display this help and exit'
complete -c gstat -l version -d 'output version information and exit '

