# gstdbuf
# Autogenerated from man page /usr/local/share/man/man1/gstdbuf.1
complete -c gstdbuf -s i -l input -d 'adjust standard input stream buffering'
complete -c gstdbuf -s o -l output -d 'adjust standard output stream buffering'
complete -c gstdbuf -s e -l error -d 'adjust standard error stream buffering'
complete -c gstdbuf -l help -d 'display this help and exit'
complete -c gstdbuf -l version -d 'output version information and exit'

