# gsum
# Autogenerated from man page /usr/local/share/man/man1/gsum.1
complete -c gsum -s r -d 'use BSD sum algorithm, use 1K blocks'
complete -c gsum -s s -l sysv -d 'use System V sum algorithm, use 512 bytes blocks'
complete -c gsum -l help -d 'display this help and exit'
complete -c gsum -l version -d 'output version information and exit AUTHOR Written by Kayvan Aghaiepour and D…'

