# gsync
# Autogenerated from man page /usr/local/share/man/man1/gsync.1
complete -c gsync -s d -l data -d 'sync only file data, no unneeded metadata'
complete -c gsync -s f -l file-system -d 'sync the file systems that contain the files'
complete -c gsync -l help -d 'display this help and exit'
complete -c gsync -l version -d 'output version information and exit'

