# gtail
# Autogenerated from man page /usr/local/share/man/man1/gtail.1
complete -c gtail -s c -l bytes -d 'output the last NUM bytes; or use -c +NUM to output starting with byte NUM of…'
complete -c gtail -s f -l follow -d 'output appended data as the file grows; P an absent option argument means \'de…'
complete -c gtail -s F -d 'same as --follow=\\,name\\/ --retry'
complete -c gtail -s n -l lines -d 'output the last NUM lines, instead of the last 10; or use -n +NUM to output s…'
complete -c gtail -l max-unchanged-stats -d 'with --follow=\\,name\\/, reopen a FILE which has not P changed size after N (d…'
complete -c gtail -l pid -d 'with -f, terminate after process ID, PID dies'
complete -c gtail -s q -l quiet -l silent -d 'never output headers giving file names'
complete -c gtail -l retry -d 'keep trying to open a file if it is inaccessible'
complete -c gtail -s s -l sleep-interval -d 'with -f, sleep for approximately N seconds (default 1'
complete -c gtail -s v -l verbose -d 'always output headers giving file names'
complete -c gtail -s z -l zero-terminated -d 'line delimiter is NUL, not newline'
complete -c gtail -l help -d 'display this help and exit'
complete -c gtail -l version -d 'output version information and exit'

