# gtee
# Autogenerated from man page /usr/local/share/man/man1/gtee.1
complete -c gtee -s a -l append -d 'append to the given FILEs, do not overwrite'
complete -c gtee -s i -l ignore-interrupts -d 'ignore interrupt signals'
complete -c gtee -s p -d 'diagnose errors writing to non pipes'
complete -c gtee -l output-error -d 'set behavior on write error.   See MODE below'
complete -c gtee -l help -d 'display this help and exit'
complete -c gtee -l version -d 'output version information and exit '

