# gtouch
# Autogenerated from man page /usr/local/share/man/man1/gtouch.1
complete -c gtouch -s a -d 'change only the access time'
complete -c gtouch -s c -l no-create -d 'do not create any files'
complete -c gtouch -s d -l date -d 'parse STRING and use it instead of current time'
complete -c gtouch -s f -d '(ignored)'
complete -c gtouch -s h -l no-dereference -d 'affect each symbolic link instead of any referenced file (useful only on syst…'
complete -c gtouch -s m -d 'change only the modification time'
complete -c gtouch -s r -l reference -d 'use this file\'s times instead of current time'
complete -c gtouch -s t -d 'use [[CC]YY]MMDDhhmm[. ss] instead of current time'
complete -c gtouch -l time -d 'change the specified time: WORD is access, atime, or use: equivalent to -a WO…'
complete -c gtouch -l help -d 'display this help and exit'
complete -c gtouch -l version -d 'output version information and exit'

