# gtr
# Autogenerated from man page /usr/local/share/man/man1/gtr.1
complete -c gtr -s c -s C -l complement -d 'use the complement of SET1'
complete -c gtr -s d -l delete -d 'delete characters in SET1, do not translate'
complete -c gtr -s s -l squeeze-repeats -d 'replace each sequence of a repeated character that is listed in the last spec…'
complete -c gtr -s t -l truncate-set1 -d 'first truncate SET1 to length of SET2'
complete -c gtr -l help -d 'display this help and exit'
complete -c gtr -l version -d 'output version information and exit '

