# gtrue
# Autogenerated from man page /usr/local/share/man/man1/gtrue.1
complete -c gtrue -l help -d 'display this help and exit'
complete -c gtrue -l version -d 'output version information and exit'

