# gtruncate
# Autogenerated from man page /usr/local/share/man/man1/gtruncate.1
complete -c gtruncate -s c -l no-create -d 'do not create any files'
complete -c gtruncate -s o -l io-blocks -d 'treat SIZE as number of IO blocks instead of bytes'
complete -c gtruncate -s r -l reference -d 'base size on RFILE'
complete -c gtruncate -s s -l size -d 'set or adjust the file size by SIZE bytes'
complete -c gtruncate -l help -d 'display this help and exit'
complete -c gtruncate -l version -d 'output version information and exit'

