# gtty
# Autogenerated from man page /usr/local/share/man/man1/gtty.1
complete -c gtty -s s -l silent -l quiet -d 'print nothing, only return an exit status'
complete -c gtty -l help -d 'display this help and exit'
complete -c gtty -l version -d 'output version information and exit AUTHOR Written by David MacKenzie'

