# guname
# Autogenerated from man page /usr/local/share/man/man1/guname.1
complete -c guname -s a -l all -d 'print all information, in the following order, except omit -p and -i if unkno…'
complete -c guname -s s -l kernel-name -d 'print the kernel name'
complete -c guname -s n -l nodename -d 'print the network node hostname'
complete -c guname -s r -l kernel-release -d 'print the kernel release'
complete -c guname -s v -l kernel-version -d 'print the kernel version'
complete -c guname -s m -l machine -d 'print the machine hardware name'
complete -c guname -s p -l processor -d 'print the processor type (non-portable)'
complete -c guname -s i -l hardware-platform -d 'print the hardware platform (non-portable)'
complete -c guname -s o -l operating-system -d 'print the operating system'
complete -c guname -l help -d 'display this help and exit'
complete -c guname -l version -d 'output version information and exit AUTHOR Written by David MacKenzie'

