# gunexpand
# Autogenerated from man page /usr/local/share/man/man1/gunexpand.1
complete -c gunexpand -s a -l all -d 'convert all blanks, instead of just initial blanks'
complete -c gunexpand -l first-only -d 'convert only leading sequences of blanks (overrides -a)'
complete -c gunexpand -s t -l tabs -d 'have tabs N characters apart instead of 8 (enables -a)'
complete -c gunexpand -l help -d 'display this help and exit'
complete -c gunexpand -l version -d 'output version information and exit AUTHOR Written by David MacKenzie'

