# guniq
# Autogenerated from man page /usr/local/share/man/man1/guniq.1
complete -c guniq -s c -l count -d 'prefix lines by the number of occurrences'
complete -c guniq -s d -l repeated -d 'only print duplicate lines, one for each group'
complete -c guniq -s D -d 'print all duplicate lines'
complete -c guniq -l all-repeated -d 'like -D, but allow separating groups with an empty line; METHOD={none(default…'
complete -c guniq -s f -l skip-fields -d 'avoid comparing the first N fields'
complete -c guniq -l group -d 'show all items, separating groups with an empty line; METHOD={separate(defaul…'
complete -c guniq -s i -l ignore-case -d 'ignore differences in case when comparing'
complete -c guniq -s s -l skip-chars -d 'avoid comparing the first N characters'
complete -c guniq -s u -l unique -d 'only print unique lines'
complete -c guniq -s z -l zero-terminated -d 'line delimiter is NUL, not newline'
complete -c guniq -s w -l check-chars -d 'compare no more than N characters in lines'
complete -c guniq -l help -d 'display this help and exit'
complete -c guniq -l version -d 'output version information and exit'

