# gusers
# Autogenerated from man page /usr/local/share/man/man1/gusers.1
complete -c gusers -l help -d 'display this help and exit'
complete -c gusers -l version -d 'output version information and exit AUTHOR Written by Joseph Arceneaux and Da…'

