# gwhoami
# Autogenerated from man page /usr/local/share/man/man1/gwhoami.1
complete -c gwhoami -l help -d 'display this help and exit'
complete -c gwhoami -l version -d 'output version information and exit AUTHOR Written by Richard Mlynarik'

