# hugo-gen-autocomplete
# Autogenerated from man page /usr/local/share/man/man1/hugo-gen-autocomplete.1
complete -c hugo-gen-autocomplete -s f -l completionfile -d '	autocompletion file, defaults to stdout'
complete -c hugo-gen-autocomplete -s h -l help -d '	help for autocomplete'
complete -c hugo-gen-autocomplete -s t -l type -d '	autocompletion type (bash, zsh, fish, or powershell) OPTIONS INHERITED FROM …'
complete -c hugo-gen-autocomplete -l config -d '	config file (default is path/config. yaml|json|toml)'
complete -c hugo-gen-autocomplete -l configDir -d '	config dir'
complete -c hugo-gen-autocomplete -l debug -d '	debug output'
complete -c hugo-gen-autocomplete -s e -l environment -d '	build environment'
complete -c hugo-gen-autocomplete -l ignoreVendor -d '	ignores any _vendor directory'
complete -c hugo-gen-autocomplete -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-gen-autocomplete -l log -d '	enable Logging'
complete -c hugo-gen-autocomplete -l logFile -d '	log File path (if set, logging enabled automatically)'
complete -c hugo-gen-autocomplete -l quiet -d '	build in quiet mode'
complete -c hugo-gen-autocomplete -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-gen-autocomplete -l themesDir -d '	filesystem path to themes directory'
complete -c hugo-gen-autocomplete -s v -l verbose -d '	verbose output'
complete -c hugo-gen-autocomplete -l verboseLog -d '	verbose logging SEE ALSO'

