# hugo-check
# Autogenerated from man page /usr/local/share/man/man1/hugo-check.1
complete -c hugo-check -s h -l help -d '	help for check OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c hugo-check -l config -d '	config file (default is path/config. yaml|json|toml)'
complete -c hugo-check -l configDir -d '	config dir'
complete -c hugo-check -l debug -d '	debug output'
complete -c hugo-check -s e -l environment -d '	build environment'
complete -c hugo-check -l ignoreVendor -d '	ignores any _vendor directory'
complete -c hugo-check -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-check -l log -d '	enable Logging'
complete -c hugo-check -l logFile -d '	log File path (if set, logging enabled automatically)'
complete -c hugo-check -l quiet -d '	build in quiet mode'
complete -c hugo-check -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-check -l themesDir -d '	filesystem path to themes directory'
complete -c hugo-check -s v -l verbose -d '	verbose output'
complete -c hugo-check -l verboseLog -d '	verbose logging SEE ALSO'

