# hugo-check-ulimit
# Autogenerated from man page /usr/local/share/man/man1/hugo-check-ulimit.1
complete -c hugo-check-ulimit -s h -l help -d '	help for ulimit OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c hugo-check-ulimit -l config -d '	config file (default is path/config. yaml|json|toml)'
complete -c hugo-check-ulimit -l configDir -d '	config dir'
complete -c hugo-check-ulimit -l debug -d '	debug output'
complete -c hugo-check-ulimit -s e -l environment -d '	build environment'
complete -c hugo-check-ulimit -l ignoreVendor -d '	ignores any _vendor directory'
complete -c hugo-check-ulimit -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-check-ulimit -l log -d '	enable Logging'
complete -c hugo-check-ulimit -l logFile -d '	log File path (if set, logging enabled automatically)'
complete -c hugo-check-ulimit -l quiet -d '	build in quiet mode'
complete -c hugo-check-ulimit -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-check-ulimit -l themesDir -d '	filesystem path to themes directory'
complete -c hugo-check-ulimit -s v -l verbose -d '	verbose output'
complete -c hugo-check-ulimit -l verboseLog -d '	verbose logging SEE ALSO'

