# infokey
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/infokey.1
complete -c infokey -l output -d 'output to FILE instead of $HOME/. info'
complete -c infokey -l help -d 'display this help and exit'
complete -c infokey -l version -d 'display version information and exit'

