# mg
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/mg.1
complete -c mg -s f -d 'Run the mode command for all buffers created from arguments on the command li…'
complete -c mg -s n -d 'Turn off backup file generation'
complete -c mg -s R -d 'Files specified on the command line will be opened read-only'

