# msdos
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/msdos.util.8
complete -c msdos -s m -d mount
complete -c msdos -s n -d 'set name'
complete -c msdos -s p -d 'probe for mounting'
complete -c msdos -s u -d unmount
complete -c msdos -s k -d 'print volume UUID El Pp mountflags above are either: -bullet -compact -offset…'

