# pass-otp
# Autogenerated from man page /usr/local/share/man/man1/pass-otp.1
complete -c pass-otp -l force -s f -d add
complete -c pass-otp -s c -d 'using xclip (1) and then restore the clipboard after 45 (or PASSWORD_STORE_CL…'

