# pbs
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/pbs.8
complete -c pbs -o debug -d 'Output debugging information regarding what pbs is doing'
complete -c pbs -o dump_pboard -d 'Prints the private pasteboard containing the current Services information'
complete -c pbs -o dump_userdefs -d 'Prints the userdef cache of Services information'
complete -c pbs -o flush_pboard -d 'Erases the private pasteboard containing Services information'
complete -c pbs -o flush_userdefs -d 'Erases the userdef cache'
complete -c pbs -o flush -d 'Equivalent to -flush_pboard and -flush_userdefs, entirely resetting pbs'

