# rtsold
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/rtsold.8
complete -c rtsold -s a -d 'Autoprobe outgoing interface'
complete -c rtsold -s d -d 'Enable debugging'
complete -c rtsold -s D -d 'Enable more debugging including the printing of internal timer information'
complete -c rtsold -s f -d 'f prevents rtsold from becoming a daemon (foreground mode)'
complete -c rtsold -s m -d 'Enable mobility support'
complete -c rtsold -s 1 -d 'Perform only one probe'

