# rtsol
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/rtsol.8
complete -c rtsol -s a -d 'Autoprobe outgoing interface'
complete -c rtsol -s d -d 'Enable debugging'
complete -c rtsol -s D -d 'Enable more debugging including the printing of internal timer information'
complete -c rtsol -s f -d 'f prevents rtsol from becoming a daemon (foreground mode)'
complete -c rtsol -s m -d 'Enable mobility support'
complete -c rtsol -s 1 -d 'Perform only one probe'

