# s2p
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/s2p.1
complete -c s2p -s a -d 'A file specified as argument to the w edit command is by default opened befor…'
complete -c s2p -s e -d 'The editing commands defined by script are appended to the script'
complete -c s2p -s f -d 'Editing commands from the specified script-file are read and appended to the …'

