# screen
# Autogenerated from man page /usr/local/share/man/man1/screen.1
complete -c screen -o Logfile -d 'By default logfile name is screenlog. 0'
complete -c screen -s Q -d 'Some commands now can be queried from a remote session using this flag, e. g'
complete -c screen -s T -d 'Set the $TERM environment variable using the specified term as opposed to the…'
complete -c screen -s 4 -d 'Resolve hostnames only to IPv4 addresses'
complete -c screen -s 6 -d 'Resolve hostnames only to IPv6 addresses.  DEFAULT KEY BINDINGS'
complete -c screen -o :no -d 'r:read:w:write:x:execute ::W:own wlock:: Indicators of permissions suppressed…'
complete -c screen -o 'flow	automatic' -d '+(+)flow	flow control enabled.  Agrees with automatic control'
complete -c screen -s g -d 'option will show the windows inside any groups in that level and downwards'

