# softwareupdate
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/softwareupdate.8
complete -c softwareupdate -s l -d 'List all available updates'
complete -c softwareupdate -s i -d 'Each update specified by args is downloaded and installed'
complete -c softwareupdate -s d -d 'Each update specified by args is downloaded but not installed'
complete -c softwareupdate -l schedule -d 'Returns the per-machine automatic (background) check preference'
complete -c softwareupdate -s h -d 'Print command usage'

