# sudo
# Autogenerated from man page /usr/share/man/man8/sudo.8
complete -c sudo -s D -l chdir -d 'Run the command in the specified directory instead of the current working dir…'
complete -c sudo -s R -l chroot -d 'Change to the specified root directory (see chroot(8)) before running the com…'

