# tapi-installapi
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/tapi-installapi.1
complete -c tapi-installapi -o target
complete -c tapi-installapi -o install_name
complete -c tapi-installapi -o ObjC
complete -c tapi-installapi -o ObjC++
complete -c tapi-installapi -s x
complete -c tapi-installapi -o std
complete -c tapi-installapi -o current_version
complete -c tapi-installapi -o compatibility_version
complete -c tapi-installapi -s D
complete -c tapi-installapi -s U
complete -c tapi-installapi -o isysroot
complete -c tapi-installapi -s I
complete -c tapi-installapi -s L
complete -c tapi-installapi -s F
complete -c tapi-installapi -l verify-mode
complete -c tapi-installapi -o verify-against
complete -c tapi-installapi -s o
complete -c tapi-installapi -l demangle
complete -c tapi-installapi -l filelist
complete -c tapi-installapi -l help
complete -c tapi-installapi -o allowable_client
complete -c tapi-installapi -o reexport_install_name
complete -c tapi-installapi -o umbrella
complete -c tapi-installapi -o fno-rtti
complete -c tapi-installapi -o fprofile-instr-generate
complete -c tapi-installapi -o extra-public-header
complete -c tapi-installapi -o extra-private-header
complete -c tapi-installapi -o exclude-public-header
complete -c tapi-installapi -o exclude-private-header
complete -c tapi-installapi -o fapplication-extension
complete -c tapi-installapi -o ferror-limit
complete -c tapi-installapi -o alias_list
complete -c tapi-installapi -o 'Xarch_<arch>' -d '<arch>.  DEPRECATED OPTIONS'
complete -c tapi-installapi -o arch
complete -c tapi-installapi -o macosx_version_min
complete -c tapi-installapi -o ios_version_min
complete -c tapi-installapi -o watchos_version_min
complete -c tapi-installapi -o tvos_version_min -d 'This is set to indicate the oldest platform version that that the output is t…'

