# tapi-stubify
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/tapi-stubify.1
complete -c tapi-stubify -l no-uuids
complete -c tapi-stubify -l set-installapi-flag
complete -c tapi-stubify -l inline-private-frameworks
complete -c tapi-stubify -s o
complete -c tapi-stubify -o isysroot
complete -c tapi-stubify -l help

