# taskgated
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/taskgated.8
complete -c taskgated -s t -d 'The daemon will quit after that many seconds of inactivity'
complete -c taskgated -s i -d 'Inject the service port of taskgated into the process with the given pid, rat…'

