# tig
# Autogenerated from man page /usr/local/share/man/man1/tig.1
complete -c tig -s v -l version -d 'Show version and exit'
complete -c tig -s h -l help -d 'Show help message and exit'
complete -c tig -s C -d 'Run as if Tig was started in <path> instead of the current working directory'
complete -c tig -l stdin -d 'option is given, stdin is assumed to be a list of commit IDs and will be forw…'
complete -c tig -l pretty -d 'is given, stdin is assumed to be a "pretty=raw" formatted output similar to t…'

