# time
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/time.1
complete -c time -s l -d 'The contents of the rusage structure are printed'
complete -c time -s p -d 'The output is formatted as specified by -p1003. 2-92'

