# tldr
# Autogenerated from man page /usr/local/share/man/man1/tldr.1
complete -c tldr -s v -d 'verbose output'
complete -c tldr -l version -d 'output version information and exit'
complete -c tldr -s h -l help -d 'display help and exit'
complete -c tldr -s u -l update -d 'update local database and exit'
complete -c tldr -s c -l clear-cache -d 'remove local database and exit'
complete -c tldr -s p -l platform -d 'select platform, supported are linux / osx / sunos / common'
complete -c tldr -s r -l render -d 'render a local page for testing purposes EXIT STATUS 0 on success, any other …'

